FROM debian
# debian kamailo

RUN apt-get update
RUN apt-get install -y mysql-common kamailio kamailio-sqlite-modules 
RUN apt-get install -y nano vim bash


#vim  /etc/kamailio/kamctlrc

#SIP_DOMAIN=192.168.
#DBENGINE=SQLITE

#kamdbctl create SQLITEDB1


#/etc/default/kamailio

#/etc/init.d/kamailio start
