FROM alpine
RUN apk update
RUN apk add kamailio
RUN apk add kamailio-sqlite
RUN apk add nano vim
RUN apk add bash
#vim  /etc/kamailio/kamctlrc

#SIP_DOMAIN=192.168.
#DBENGINE=SQLITE

#vim /etc/default/kamailio

#kamdbctl create SQLITEDB1
#/etc/init.d/kamailio start

